# Generated by Django 4.2.2 on 2023-06-12 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waaam_app', '0019_profile_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerrecord',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waaam_app.activitychoice'),
        ),
    ]
