# Generated by Django 4.2.2 on 2023-06-13 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('waaam_app', '0020_alter_volunteerrecord_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerrecord',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
